WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
READ [x,z,l,v]
SHOW
BACKUP
DELETE [c]
READ [c]
a
WAIT 10000
a
SHOW
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WAIT 10000
b
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
DELETE [a]
