WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
READ [x,z,l,v]
SHOW
BACKUP
a
DELETE [c]
READ [c]
WAIT 10000
a
SHOW
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WAIT 10000
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
DELETE [a]
